// Mocks generated by Mockito 5.4.5 from annotations
// in green_check/test/useCase/save_student_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:green_check/domain/models/student.dart' as _i3;
import 'package:green_check/infrastructure/repositories/student_repository.dart'
    as _i4;
import 'package:green_check/infrastructure/services/student_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStudentService_0 extends _i1.SmartFake
    implements _i2.StudentService {
  _FakeStudentService_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeStudent_1 extends _i1.SmartFake implements _i3.Student {
  _FakeStudent_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [StudentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudentRepository extends _i1.Mock implements _i4.StudentRepository {
  MockStudentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StudentService get datasource => (super.noSuchMethod(
        Invocation.getter(#datasource),
        returnValue: _FakeStudentService_0(
          this,
          Invocation.getter(#datasource),
        ),
      ) as _i2.StudentService);

  @override
  _i5.Future<_i3.Student> saveStudent(_i3.Student? student) =>
      (super.noSuchMethod(
        Invocation.method(#saveStudent, [student]),
        returnValue: _i5.Future<_i3.Student>.value(
          _FakeStudent_1(this, Invocation.method(#saveStudent, [student])),
        ),
      ) as _i5.Future<_i3.Student>);

  @override
  dynamic authStudent(String? email, String? password) =>
      super.noSuchMethod(Invocation.method(#authStudent, [email, password]));
}
