// Mocks generated by Mockito 5.4.5 from annotations
// in green_check/test/useCase/toggle_favorite_course_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:green_check/domain/models/course.dart' as _i6;
import 'package:green_check/domain/models/user.dart' as _i3;
import 'package:green_check/infrastructure/repositories/student_course_repository.dart'
    as _i4;
import 'package:green_check/infrastructure/services/student_course_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStudentCourseService_0 extends _i1.SmartFake
    implements _i2.StudentCourseService {
  _FakeStudentCourseService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StudentCourseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudentCourseRepository extends _i1.Mock
    implements _i4.StudentCourseRepository {
  MockStudentCourseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StudentCourseService get datasource =>
      (super.noSuchMethod(
            Invocation.getter(#datasource),
            returnValue: _FakeStudentCourseService_0(
              this,
              Invocation.getter(#datasource),
            ),
          )
          as _i2.StudentCourseService);

  @override
  _i5.Future<List<_i3.User>> getStudents(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudents, [courseId]),
            returnValue: _i5.Future<List<_i3.User>>.value(<_i3.User>[]),
          )
          as _i5.Future<List<_i3.User>>);

  @override
  _i5.Future<List<_i6.Course>> getCoursesForStudent(String? idStudent) =>
      (super.noSuchMethod(
            Invocation.method(#getCoursesForStudent, [idStudent]),
            returnValue: _i5.Future<List<_i6.Course>>.value(<_i6.Course>[]),
          )
          as _i5.Future<List<_i6.Course>>);

  @override
  _i5.Future<void> deleteStudent(String? idStudent, String? idCourse) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStudent, [idStudent, idCourse]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleFavorite(
    String? courseId,
    bool? isFavorite,
    String? idStudent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [
              courseId,
              isFavorite,
              idStudent,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.User> saveStudent(String? courseId, String? idStudent) =>
      (super.noSuchMethod(
            Invocation.method(#saveStudent, [courseId, idStudent]),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_1(
                this,
                Invocation.method(#saveStudent, [courseId, idStudent]),
              ),
            ),
          )
          as _i5.Future<_i3.User>);
}
