// Mocks generated by Mockito 5.4.5 from annotations
// in green_check/test/useCase/delete_course_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:green_check/domain/models/course.dart' as _i4;
import 'package:green_check/infrastructure/repositories/course_repository.dart'
    as _i3;
import 'package:green_check/infrastructure/services/course_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCourseService_0 extends _i1.SmartFake implements _i2.CourseService {
  _FakeCourseService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CourseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRepository extends _i1.Mock implements _i3.CourseRepository {
  MockCourseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CourseService get datasource =>
      (super.noSuchMethod(
            Invocation.getter(#datasource),
            returnValue: _FakeCourseService_0(
              this,
              Invocation.getter(#datasource),
            ),
          )
          as _i2.CourseService);

  @override
  dynamic saveCourse(_i4.Course? student) =>
      super.noSuchMethod(Invocation.method(#saveCourse, [student]));

  @override
  dynamic getCourses(String? idTeacher) =>
      super.noSuchMethod(Invocation.method(#getCourses, [idTeacher]));

  @override
  dynamic getCourse(String? idStudent) =>
      super.noSuchMethod(Invocation.method(#getCourse, [idStudent]));

  @override
  _i5.Future<void> deleteCourse(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCourse, [courseId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
