// Mocks generated by Mockito 5.4.5 from annotations
// in green_check/test/useCase/delete_test_use__case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:green_check/domain/models/question.dart' as _i6;
import 'package:green_check/domain/models/test.dart' as _i3;
import 'package:green_check/infrastructure/repositories/test_repository.dart'
    as _i4;
import 'package:green_check/infrastructure/services/test_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTestService_0 extends _i1.SmartFake implements _i2.TestService {
  _FakeTestService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTest_1 extends _i1.SmartFake implements _i3.Test {
  _FakeTest_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestRepository extends _i1.Mock implements _i4.TestRepository {
  MockTestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TestService get datasource =>
      (super.noSuchMethod(
            Invocation.getter(#datasource),
            returnValue: _FakeTestService_0(
              this,
              Invocation.getter(#datasource),
            ),
          )
          as _i2.TestService);

  @override
  _i5.Future<List<_i3.Test>> getTests(String? idCourse) =>
      (super.noSuchMethod(
            Invocation.method(#getTests, [idCourse]),
            returnValue: _i5.Future<List<_i3.Test>>.value(<_i3.Test>[]),
          )
          as _i5.Future<List<_i3.Test>>);

  @override
  _i5.Future<dynamic> createTest<Test>(String? title, String? idCourse) =>
      (super.noSuchMethod(
            Invocation.method(#createTest, [title, idCourse]),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  dynamic saveQuestions(List<_i6.Question>? questionsToSave, String? id) =>
      super.noSuchMethod(
        Invocation.method(#saveQuestions, [questionsToSave, id]),
      );

  @override
  void deleteTest(String? idTest, String? idCourse) => super.noSuchMethod(
    Invocation.method(#deleteTest, [idTest, idCourse]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i6.Question>> getQuestions(String? testId) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestions, [testId]),
            returnValue: _i5.Future<List<_i6.Question>>.value(<_i6.Question>[]),
          )
          as _i5.Future<List<_i6.Question>>);

  @override
  _i5.Future<List<_i3.Test>> getTestsByIds(List<String>? testIds) =>
      (super.noSuchMethod(
            Invocation.method(#getTestsByIds, [testIds]),
            returnValue: _i5.Future<List<_i3.Test>>.value(<_i3.Test>[]),
          )
          as _i5.Future<List<_i3.Test>>);

  @override
  _i5.Future<_i3.Test> getTest(String? testId) =>
      (super.noSuchMethod(
            Invocation.method(#getTest, [testId]),
            returnValue: _i5.Future<_i3.Test>.value(
              _FakeTest_1(this, Invocation.method(#getTest, [testId])),
            ),
          )
          as _i5.Future<_i3.Test>);
}
