// Mocks generated by Mockito 5.4.5 from annotations
// in green_check/test/useCase/get_notices_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:green_check/domain/models/course.dart' as _i11;
import 'package:green_check/domain/models/notice.dart' as _i3;
import 'package:green_check/domain/usecases/get_courses_student_use_case.dart'
    as _i10;
import 'package:green_check/domain/usecases/get_courses_teacher_use_case.dart'
    as _i12;
import 'package:green_check/infrastructure/repositories/course_repository.dart'
    as _i7;
import 'package:green_check/infrastructure/repositories/notice_repository.dart'
    as _i8;
import 'package:green_check/infrastructure/repositories/student_course_repository.dart'
    as _i4;
import 'package:green_check/infrastructure/repositories/student_repository.dart'
    as _i5;
import 'package:green_check/infrastructure/repositories/teacher_repository.dart'
    as _i6;
import 'package:green_check/infrastructure/services/notice_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNoticeService_0 extends _i1.SmartFake implements _i2.NoticeService {
  _FakeNoticeService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotice_1 extends _i1.SmartFake implements _i3.Notice {
  _FakeNotice_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudentCourseRepository_2 extends _i1.SmartFake
    implements _i4.StudentCourseRepository {
  _FakeStudentCourseRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudentRepository_3 extends _i1.SmartFake
    implements _i5.StudentRepository {
  _FakeStudentRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTeacherRepository_4 extends _i1.SmartFake
    implements _i6.TeacherRepository {
  _FakeTeacherRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCourseRepository_5 extends _i1.SmartFake
    implements _i7.CourseRepository {
  _FakeCourseRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NoticeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoticeRepository extends _i1.Mock implements _i8.NoticeRepository {
  MockNoticeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoticeService get datasource =>
      (super.noSuchMethod(
            Invocation.getter(#datasource),
            returnValue: _FakeNoticeService_0(
              this,
              Invocation.getter(#datasource),
            ),
          )
          as _i2.NoticeService);

  @override
  _i9.Future<List<_i3.Notice>> getNotices(List<String?>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getNotices, [ids]),
            returnValue: _i9.Future<List<_i3.Notice>>.value(<_i3.Notice>[]),
          )
          as _i9.Future<List<_i3.Notice>>);

  @override
  _i9.Future<_i3.Notice> saveNotice(_i3.Notice? notice) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotice, [notice]),
            returnValue: _i9.Future<_i3.Notice>.value(
              _FakeNotice_1(this, Invocation.method(#saveNotice, [notice])),
            ),
          )
          as _i9.Future<_i3.Notice>);
}

/// A class which mocks [GetCoursesStudentUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCoursesStudentUseCase extends _i1.Mock
    implements _i10.GetCoursesStudentUseCase {
  MockGetCoursesStudentUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.StudentCourseRepository get studentCourseRepository =>
      (super.noSuchMethod(
            Invocation.getter(#studentCourseRepository),
            returnValue: _FakeStudentCourseRepository_2(
              this,
              Invocation.getter(#studentCourseRepository),
            ),
          )
          as _i4.StudentCourseRepository);

  @override
  _i5.StudentRepository get studentRepository =>
      (super.noSuchMethod(
            Invocation.getter(#studentRepository),
            returnValue: _FakeStudentRepository_3(
              this,
              Invocation.getter(#studentRepository),
            ),
          )
          as _i5.StudentRepository);

  @override
  _i6.TeacherRepository get teacherRepository =>
      (super.noSuchMethod(
            Invocation.getter(#teacherRepository),
            returnValue: _FakeTeacherRepository_4(
              this,
              Invocation.getter(#teacherRepository),
            ),
          )
          as _i6.TeacherRepository);

  @override
  _i9.Future<List<_i11.Course>> execute(String? idStudent) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [idStudent]),
            returnValue: _i9.Future<List<_i11.Course>>.value(<_i11.Course>[]),
          )
          as _i9.Future<List<_i11.Course>>);
}

/// A class which mocks [GetCoursesTeacherUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCoursesTeacherUseCase extends _i1.Mock
    implements _i12.GetCoursesTeacherUseCase {
  MockGetCoursesTeacherUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CourseRepository get courseRepository =>
      (super.noSuchMethod(
            Invocation.getter(#courseRepository),
            returnValue: _FakeCourseRepository_5(
              this,
              Invocation.getter(#courseRepository),
            ),
          )
          as _i7.CourseRepository);

  @override
  _i9.Future<List<_i11.Course>> execute(String? idTeacher) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [idTeacher]),
            returnValue: _i9.Future<List<_i11.Course>>.value(<_i11.Course>[]),
          )
          as _i9.Future<List<_i11.Course>>);
}
