// Mocks generated by Mockito 5.4.5 from annotations
// in green_check/test/useCase/save_notice_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:green_check/domain/models/notice.dart' as _i3;
import 'package:green_check/infrastructure/repositories/notice_repository.dart'
    as _i4;
import 'package:green_check/infrastructure/services/notice_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNoticeService_0 extends _i1.SmartFake implements _i2.NoticeService {
  _FakeNoticeService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotice_1 extends _i1.SmartFake implements _i3.Notice {
  _FakeNotice_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NoticeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoticeRepository extends _i1.Mock implements _i4.NoticeRepository {
  MockNoticeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoticeService get datasource =>
      (super.noSuchMethod(
            Invocation.getter(#datasource),
            returnValue: _FakeNoticeService_0(
              this,
              Invocation.getter(#datasource),
            ),
          )
          as _i2.NoticeService);

  @override
  _i5.Future<List<_i3.Notice>> getNotices(List<String?>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getNotices, [ids]),
            returnValue: _i5.Future<List<_i3.Notice>>.value(<_i3.Notice>[]),
          )
          as _i5.Future<List<_i3.Notice>>);

  @override
  _i5.Future<_i3.Notice> saveNotice(_i3.Notice? notice) =>
      (super.noSuchMethod(
            Invocation.method(#saveNotice, [notice]),
            returnValue: _i5.Future<_i3.Notice>.value(
              _FakeNotice_1(this, Invocation.method(#saveNotice, [notice])),
            ),
          )
          as _i5.Future<_i3.Notice>);
}
